### ISSUE TITLE
gradle wrapper outdated?

### ISSUE THREAD

**Issue by IzzySoft** [nikita-yfh/android-adb-tools#7]
your [`gradle-wrapper.properties`](https://github.com/nikita-yfh/android-adb-tools/blob/noroot/gradle/wrapper/gradle-wrapper.properties) states

     distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip

which cannot be true, as your project uses JDK 17, which is not supported by that ancient gradle version. Could it be the wrapper is outdated, and you just forgot to replace it? You can impossibly have compiled the app with that. According to [your workflow](
https://github.com/nikita-yfh/android-adb-tools/blob/noroot/.github/workflows/android.yml#L42) you use JDK 18 with that gradle even – I cannot fathom how that should work :wink: Java 17 would require gradle 7.3+, Java 18 even 7.5+.

Any chance you could update the gradle wrapper? Probably the [change here](https://github.com/nikita-yfh/android-adb-tools/commit/9cce6bd7c810aa9ada4e3ab5687c094dd2b28745) from 7.0 to 3.3 was a typo, and you meant 8.3? Thanks in advance!

PS: I've tried building v1.5.1 with injecting gradle 8.9, but the build failed:

```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.android.tools.build:gradle:2.2.3.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.pom
     Required by:
         project :
```

JCenter is dead. Maybe you can use [a newer version](https://mvnrepository.com/artifact/com.android.tools.build/gradle) of the plugin? There are several available from Google's Maven.

**Comment by nikita-yfh** [comment]
Can you make pull request?

**Comment by IzzySoft** [comment]
I'm no Android dev, sorry – I just try to compile from source and interpret the errors. I don't even know which gradle version you'd need (or used to compile the current APK).

For some background: At IzzyOnDroid (where your app is [currently listed](https://apt.izzysoft.de/packages/ru.nikita.adb) – be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) and link there e.g. from your Readme) we support [Reproducible Builds](https://reproducible-builds.org/) (see: [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)). For that, we need to be able to compile from your source.

We'd appreciate if you could help making your build reproducible. We've prepared some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) for that.

Looking forward to your reply!

cc @obfusk

**Comment by obfusk** [comment]
It looks like that workflow was never run. And Android Gradle Plugin 2.2.3 -- which I doubt was ever on JCenter as Google uses their own maven repo -- is from 2016/2017. That would match Gradle 3.3 (presumably built with Java 8). I also see `minSdkVersion 12` and `targetSdkVersion 20`, suggesting the app is indeed using a pretty old toolchain. Which likely means Reproducible Builds won't be possible.

**Comment by IzzySoft** [comment]
Thanks Fay!

@nikita-yfh any plans to lift that up? If not, I'd say we have to drop the app from our RB queue (RB is not mandatory, just strongly recommended). No bad feelings if that's what you prefer, though a matching update would be what we prefer :wink:

**Comment by nikita-yfh** [comment]
I have deleted the new PR from the history.
Then I was sure that the new PR would not break anything, and after that I did not check compilation, it's my mistake.
This version must compile.

**Comment by IzzySoft** [comment]
I don't see a new commit – maybe you forgot to push? Also, we'd then need a matching APK (built from that commit) to compare against. Thanks!

**Comment by IzzySoft** [comment]
PS, as there might be a slight misunderstanding: we were not using any Github CI there. We use this recipe:

```yaml
---
repository: https://github.com/nikita-yfh/android-adb-tools.git
updates: releases
versions:
  - tag: 1.5.1
    apks:
      - apk_pattern: apprelease\.apk
        apk_url: https://github.com/nikita-yfh/android-adb-tools/releases/download/1.5.1/app-release.apk
        build:
          - ./gradlew assembleRelease
          - find . -name '*.apk'
          - mv app/build/outputs/apk/release/*unsigned.apk /outputs/unsigned.apk
        build_home_dir: /build
        build_repo_dir: /build/repo
        build_user: build
        provisioning:
          android_home: /opt/sdk
          build_tools:
          cmake:
          cmdline_tools:
            version: '12.0'
            url: https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
            sha256: 2d2d50857e4eb553af5a6dc3ad507a17adf43d115264b1afc116f95c92e5e258
          extra_packages: []
          image: debian:bookworm-slim
          jdk: openjdk-17-jdk-headless
          ndk:
          platform:
          platform_tools:
          tools:
          verify_gradle_wrapper: true
```

with [rbtlog](https://github.com/obfusk/rbtlog) as the task is about confirming [Reproducible Builds](https://reproducible-builds.org/), also see [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients) (as mentioned above).
